[server]
headless = true
enableCORS = false
port = 8501
enableXsrfProtection = false

[theme]
primaryColor = "#4A90E2"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F5"
textColor = "#000000"
font = "sans serif"
